apiVersion: apps/v1
kind: Deployment
metadata:
  name: drones-app
spec:
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: drones-app
  template:
    metadata:
      labels:
        app: drones-app
    spec:
      containers:
      - name: drones-app
        image: us-central1-docker.pkg.dev/ai-powered-btos/registry/drones-api:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
